In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('train.csv')

# Display the first 10 rows
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [48]:
#show the shape of the data (number of rows and columns
print("Dataset shape:", df.shape)

Dataset shape: (1460, 83)

In [7]:
#Handle Missing Values

# Check missing values
missing_values = df.isnull().sum()

print("Columns with missing values:", (df.isnull().sum() > 0).sum())

print()

# Display only columns that have missing values
print(missing_values[missing_values > 0].sort_values(ascending=False))

Columns with missing values: 19

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
dtype: int64

**columns description**

SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict.
MSSubClass: The building class
MSZoning: The general zoning classification
LotFrontage: Linear feet of street connected to property
LotArea: Lot size in square feet
Street: Type of road access
Alley: Type of alley access
LotShape: General shape of property
LandContour: Flatness of the property
Utilities: Type of utilities available
LotConfig: Lot configuration
LandSlope: Slope of property
Neighborhood: Physical locations within Ames city limits
Condition1: Proximity to main road or railroad
Condition2: Proximity to main road or railroad (if a second is present)
BldgType: Type of dwelling
HouseStyle: Style of dwelling
OverallQual: Overall material and finish quality
OverallCond: Overall condition rating
YearBuilt: Original construction date
YearRemodAdd: Remodel date
RoofStyle: Type of roof
RoofMatl: Roof material
Exterior1st: Exterior covering on house
Exterior2nd: Exterior covering on house (if more than one material)
MasVnrType: Masonry veneer type
MasVnrArea: Masonry veneer area in square feet
ExterQual: Exterior material quality
ExterCond: Present condition of the material on the exterior
Foundation: Type of foundation
BsmtQual: Height of the basement
BsmtCond: General condition of the basement
BsmtExposure: Walkout or garden level basement walls
BsmtFinType1: Quality of basement finished area
BsmtFinSF1: Type 1 finished square feet
BsmtFinType2: Quality of second finished area (if present)
BsmtFinSF2: Type 2 finished square feet
BsmtUnfSF: Unfinished square feet of basement area
TotalBsmtSF: Total square feet of basement area
Heating: Type of heating
HeatingQC: Heating quality and condition
CentralAir: Central air conditioning
Electrical: Electrical system
1stFlrSF: First Floor square feet
2ndFlrSF: Second floor square feet
LowQualFinSF: Low quality finished square feet (all floors)
GrLivArea: Above grade (ground) living area square feet
BsmtFullBath: Basement full bathrooms
BsmtHalfBath: Basement half bathrooms
FullBath: Full bathrooms above grade
HalfBath: Half baths above grade
Bedroom: Number of bedrooms above basement level
Kitchen: Number of kitchens
KitchenQual: Kitchen quality
TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
Functional: Home functionality rating
Fireplaces: Number of fireplaces
FireplaceQu: Fireplace quality
GarageType: Garage location
GarageYrBlt: Year garage was built
GarageFinish: Interior finish of the garage
GarageCars: Size of garage in car capacity
GarageArea: Size of garage in square feet
GarageQual: Garage quality
GarageCond: Garage condition
PavedDrive: Paved driveway
WoodDeckSF: Wood deck area in square feet
OpenPorchSF: Open porch area in square feet
EnclosedPorch: Enclosed porch area in square feet
3SsnPorch: Three season porch area in square feet
ScreenPorch: Screen porch area in square feet
PoolArea: Pool area in square feet
PoolQC: Pool quality
Fence: Fence quality
MiscFeature: Miscellaneous feature not covered in other categories
MiscVal: $Value of miscellaneous feature
MoSold: Month Sold
YrSold: Year Sold
SaleType: Type of sale
SaleCondition: Condition of sale

**identify the numerical and categorical features**

In [13]:
# Identify numerical columns
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

# Identify categorical columns
categorical_columns = df.select_dtypes(
    include=["object", "str"]
).columns

print("Numerical columns:", len(numerical_columns))
print("Categorical columns:", len(categorical_columns))

Numerical columns: 38
Categorical columns: 43

There are 38 numerical columns and 43 catagorical columns.

Impute numerical missing values using the median

In [14]:
from sklearn.impute import SimpleImputer

# Create median imputer
num_imputer = SimpleImputer(strategy="median")

# Fill missing numerical values
df[numerical_columns] = num_imputer.fit_transform(
    df[numerical_columns]
)

**Impute categorical missing values using the most frequent category**

In [15]:
# Create most-frequent imputer
cat_imputer = SimpleImputer(strategy="most_frequent")

# Fill missing categorical values
df[categorical_columns] = cat_imputer.fit_transform(
    df[categorical_columns]
)

In [16]:
#verify the missing values are 
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [20]:
# Identify numerical features
numerical_features = df.select_dtypes(
    include=["int64", "float64"]
).columns

print("Number of numerical features:", len(numerical_features))
print(numerical_features.tolist())

Number of numerical features: 38
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']

In [21]:
#drop the id and salesprice column: dropping ID because it has no impact on the dataset and sales price because it is the target variable
numerical_features = numerical_features.drop(
    ["Id", "SalePrice"]
)

print(numerical_features.tolist())

['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold']

In [22]:
#Apply teh minMax scaller
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[numerical_features] = scaler.fit_transform(
    df[numerical_features]
)

In [24]:
#show teh outcome
df[numerical_features].head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,0.235294,0.150685,0.033420,0.666667,0.500,0.949275,0.883333,0.12250,0.125089,0.0,...,0.386460,0.000000,0.111517,0.000000,0.0,0.0,0.0,0.0,0.090909,0.50
1,0.000000,0.202055,0.038795,0.555556,0.875,0.753623,0.433333,0.00000,0.173281,0.0,...,0.324401,0.347725,0.000000,0.000000,0.0,0.0,0.0,0.0,0.363636,0.25
2,0.235294,0.160959,0.046507,0.666667,0.500,0.934783,0.866667,0.10125,0.086109,0.0,...,0.428773,0.000000,0.076782,0.000000,0.0,0.0,0.0,0.0,0.727273,0.50
3,0.294118,0.133562,0.038561,0.666667,0.500,0.311594,0.333333,0.00000,0.038271,0.0,...,0.452750,0.000000,0.063985,0.492754,0.0,0.0,0.0,0.0,0.090909,0.00
4,0.235294,0.215753,0.060576,0.777778,0.500,0.927536,0.833333,0.21875,0.116052,0.0,...,0.589563,0.224037,0.153565,0.000000,0.0,0.0,0.0,0.0,1.000000,0.50

In [25]:
print(df[numerical_features].min())
print(df[numerical_features].max())

MSSubClass       0.0
LotFrontage      0.0
LotArea          0.0
OverallQual      0.0
OverallCond      0.0
YearBuilt        0.0
YearRemodAdd     0.0
MasVnrArea       0.0
BsmtFinSF1       0.0
BsmtFinSF2       0.0
BsmtUnfSF        0.0
TotalBsmtSF      0.0
1stFlrSF         0.0
2ndFlrSF         0.0
LowQualFinSF     0.0
GrLivArea        0.0
BsmtFullBath     0.0
BsmtHalfBath     0.0
FullBath         0.0
HalfBath         0.0
BedroomAbvGr     0.0
KitchenAbvGr     0.0
TotRmsAbvGrd     0.0
Fireplaces       0.0
GarageYrBlt      0.0
GarageCars       0.0
GarageArea       0.0
WoodDeckSF       0.0
OpenPorchSF      0.0
EnclosedPorch    0.0
3SsnPorch        0.0
ScreenPorch      0.0
PoolArea         0.0
MiscVal          0.0
MoSold           0.0
YrSold           0.0
dtype: float64
MSSubClass       1.0
LotFrontage      1.0
LotArea          1.0
OverallQual      1.0
OverallCond      1.0
YearBuilt        1.0
YearRemodAdd     1.0
MasVnrArea       1.0
BsmtFinSF1       1.0
BsmtFinSF2       1.0
BsmtUnfSF        1.0
TotalBsmtSF      1.0
1stFlrSF         1.0
2ndFlrSF         1.0
LowQualFinSF     1.0
GrLivArea        1.0
BsmtFullBath     1.0
BsmtHalfBath     1.0
FullBath         1.0
HalfBath         1.0
BedroomAbvGr     1.0
KitchenAbvGr     1.0
TotRmsAbvGrd     1.0
Fireplaces       1.0
GarageYrBlt      1.0
GarageCars       1.0
GarageArea       1.0
WoodDeckSF       1.0
OpenPorchSF      1.0
EnclosedPorch    1.0
3SsnPorch        1.0
ScreenPorch      1.0
PoolArea         1.0
MiscVal          1.0
MoSold           1.0
YrSold           1.0
dtype: float64

In [26]:
# Identify categorical features
categorical_features = df.select_dtypes(
    include=["str"]
).columns

print("Number of categorical features:", len(categorical_features))
print(categorical_features.tolist())

Number of categorical features: 43
['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition']

In [27]:
#using one hot encoding tecchnique
df_encoded = pd.get_dummies(
    df,
    columns=categorical_features,
    dtype=int
)

df_encoded.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1.0,0.235294,0.150685,0.033420,0.666667,0.500,0.949275,0.883333,0.12250,0.125089,...,0,0,0,1,0,0,0,0,1,0
1,2.0,0.000000,0.202055,0.038795,0.555556,0.875,0.753623,0.433333,0.00000,0.173281,...,0,0,0,1,0,0,0,0,1,0
2,3.0,0.235294,0.160959,0.046507,0.666667,0.500,0.934783,0.866667,0.10125,0.086109,...,0,0,0,1,0,0,0,0,1,0
3,4.0,0.294118,0.133562,0.038561,0.666667,0.500,0.311594,0.333333,0.00000,0.038271,...,0,0,0,1,1,0,0,0,0,0
4,5.0,0.235294,0.215753,0.060576,0.777778,0.500,0.927536,0.833333,0.21875,0.116052,...,0,0,0,1,0,0,0,0,1,0

**Feature Engineering**

Since i already imputed the missing values with the entire dataset,if i go ahead and train that data, it will create a data leakage since the data is already exposed. Therefore, so to prevent this, i will relaod the original dataset.

In [28]:
# Reload the original dataset
df = pd.read_csv("train.csv")

In [29]:
# Create TotalSF
df["TotalSF"] = (
    df["TotalBsmtSF"] +
    df["1stFlrSF"] +
    df["2ndFlrSF"]
)

df[["TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "TotalSF"]].head()

   TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSF
0          856       856       854     2566
1         1262      1262         0     2524
2          920       920       866     2706
3          756       961       756     2473
4         1145      1145      1053     3343

In [30]:
# Create Age
df["Age"] = df["YrSold"] - df["YearBuilt"]

df[["YearBuilt", "YrSold", "Age"]].head()

   YearBuilt  YrSold  Age
0       2003    2008    5
1       1976    2007   31
2       2001    2008    7
3       1915    2006   91
4       2000    2008    8

In [31]:
#verify both features created
df[["TotalSF", "Age"]].head(10)

   TotalSF  Age
0     2566    5
1     2524   31
2     2706    7
3     2473   91
4     3343    8
5     2158   16
6     3380    3
7     3197   36
8     2726   77
9     2068   69

**Split the Dataset to Prevent Data Leakage**

In [33]:
# Separate features and target
X = df.drop(columns=["SalePrice", "Id"])
y = df["SalePrice"]

SalePrice is removed from X because it is the target varaible (what we are trying to predict). Id is also removed because it is primarily an identifier rather than a meaningful house characteristic.

In [36]:
#80/20 split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (1168, 81)
X_test: (292, 81)
y_train: (1168,)
y_test: (292,)

In [38]:
#perform the MinMax scaler on just the training dataset
from sklearn.preprocessing import MinMaxScaler

# Identify numerical features
numerical_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns

X_train_numeric = X_train[numerical_features]
X_test_numeric = X_test[numerical_features]

# Median imputation
num_imputer = SimpleImputer(strategy="median")

X_train_numeric = num_imputer.fit_transform(X_train_numeric)
X_test_numeric = num_imputer.transform(X_test_numeric)

# Min-Max scaling
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train_numeric)
X_test_scaled = scaler.transform(X_test_numeric)

In [41]:
#On the categorical variables
X_train_categorical = X_train[categorical_features]
X_test_categorical = X_test[categorical_features]

cat_imputer = SimpleImputer(strategy="most_frequent")

# Fit on training data
X_train_categorical = cat_imputer.fit_transform(
    X_train_categorical
)

# Transform test data
X_test_categorical = cat_imputer.transform(
    X_test_categorical
)

In [42]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

# Fit encoder ONLY on training data
X_train_encoded = encoder.fit_transform(
    X_train_categorical
)

# Apply same encoder to test data
X_test_encoded = encoder.transform(
    X_test_categorical
)

To prevent data leakage, i reloaded the original dataset, then split the dataset into 80% training data and 20% testing data before fitting the preprocessing methods. Missing-value imputation, Min-Max scaling, and One-Hot Encoding should be fitted only on the training data. The fitted transformations are then applied to the test data without using information from the test set. This ensures that the model is evaluated on unseen data and provides a more reliable measure of its performance.

In [44]:
import numpy as np
# Combine numerical and categorical training features
X_train_preprocessed = np.hstack(
    (X_train_scaled, X_train_encoded)
)

# Combine numerical and categorical test features
X_test_preprocessed = np.hstack(
    (X_test_scaled, X_test_encoded)
)

print("Training shape:", X_train_preprocessed.shape)
print("Testing shape:", X_test_preprocessed.shape)

Training shape: (1168, 287)
Testing shape: (292, 287)

**Train the Linear Regression model**

In [45]:
from sklearn.linear_model import LinearRegression

# Create the model
model = LinearRegression()

# Train the model
model.fit(X_train_preprocessed, y_train)

LinearRegression()

In [46]:
# Training predictions
y_train_pred = model.predict(X_train_preprocessed)

# Test predictions
y_test_pred = model.predict(X_test_preprocessed)

In [47]:
#calculate the mse
from sklearn.metrics import mean_squared_error

# Calculate MSE
train_mse = mean_squared_error(
    y_train,
    y_train_pred
)

test_mse = mean_squared_error(
    y_test,
    y_test_pred
)

print("Training MSE:", train_mse)
print("Test MSE:", test_mse)

Training MSE: 381425292.45028925
Test MSE: 868806561.3061415

The Linear Regression model achieved a training MSE of 381,425,292.45 and a test MSE of 868,806,561.31. The higher test MSE indicates that the model performs less accurately on unseen data and suggests some overfitting

In [50]:
#Calculate training and testing RMSE
train_rmse = np.sqrt(train_mse)
test_rmse = np.sqrt(test_mse)

print("Training RMSE:", train_rmse)
print("Test RMSE:", test_rmse)

Training RMSE: 19530.1124536007
Test RMSE: 29475.524784236524

The Linear Regression model achieved a training RMSE of $19,530.11 and a test RMSE of $29,475.59. The higher test RMSE shows that the model performs better on the training data than on unseen data. This suggests some overfitting. $29,475.59 on the test data indicates that the model's predicted house sale prices typically deviate from the actual SalePrice by $29,476, with larger prediction errors being penalized more heavily.